cli: Add `generate` command.
hashicorp/nomad-pack pull request #222
Opened 2022-03-11 02:30 UTC by angrycub

**Description**

 Using the `nomad-pack generate` command,  users will be able to generate a sample pack or registry using built-in starting artifacts.

**Reminders**

- [x] Add `CHANGELOG.md` entry

2022-03-12 18:25 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad-pack?pullRequest=222)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad-pack?pullRequest=222)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad-pack?pullRequest=222).</sub>

2022-03-14 12:38 UTC, DerekStrickland requested changes
I left a bit of feedback.  I also am wondering if a new pack should be runnable after generation.  Currently, I receive the following error.

```shell
! Failed To Process Pack

        Error:   template: pr-test/templates/_helpers.tpl:3: bad character U+002D '-'
        Type:    *errors.errorString
        Context: 
                 - Registry Name: <<local folder>>
                 - Pack Name: pr-test
                 - Pack Ref: <<none>>
                 - Pack Path: /Users/derekstrickland/goland/nomad-pack/pr-test
                 - Deployment Name: pr-test
```

2022-03-14 16:08 UTC, angrycub commented on internal/cli/generate_help.go
> +	c.cmdKey = "generate"
:shrug: It doesn't show up as dead code, and I haven't pulled that particular thread.  I can look into that in a separate effort.  Made issue #233 to track

2022-03-14 16:08 UTC, angrycub commented on internal/creator/templates/pack_metadata.hcl
> +# }
```suggestion
# }

```

2022-03-14 18:03 UTC, DerekStrickland approved these changes
LGTM

2022-03-14 19:43 UTC, merged