Use shallow cloning to add pack registries
hashicorp/nomad-pack pull request #444
Opened 2023-10-20 13:02 UTC by attachmentgenie

We use a mono repo to build out all of our platforms, as a down side of this our git history and .git directory are huge (think 10x the actual code size)which causes git clones to be quite slow.

This PR switches the git clone behaviour of `nomad-pack registry add` to use shallow clone instead. In our particular case it drops the length of the process from ~9s to 0.5s.

**Reminders**

- [x] Add `CHANGELOG.md` entry

2023-10-24 15:58 UTC, pkazmierczak requested changes
Thanks for the PR @attachmentgenie! This is good thinking, in many scenarios (big repo, using pack in CI) a shallow clone makes much more sense than a full clone. However, shallow clones affect what we can do with the repository, and that's why I'd prefer shallow-cloning to be a flag. 

For example, if we were to support updating registries, we'd have to introduce special treatment for shallow-cloned repositories, and their updates would take much longer. Secondly, users might want to switch branches of their registries (granted, a niche use-case, but possible with current implementation and defaulting to shallow-clones would  break it). 

I don't have a strong opinion on whether this should be an opt-in or an opt-out flag, perhaps @angrycub has an opinion? But I think it should be a flag nonetheless.

2023-10-24 15:58 UTC, pkazmierczak commented on internal/pkg/cache/add.go
> +		url = fmt.Sprintf("%s?depth=1", url)
I'd rather have the shallow clone be a a flag to the add command than handling it this way.

2023-10-24 20:11 UTC, attachmentgenie commented
I debated with myself about feature flagging it but ultimately (lazily) decided not to do it because as long as , [this bit of code](https://github.com/hashicorp/nomad-pack/blob/db9f7f8c84da83f267d9f6c4d1d103ba7c395a7c/internal/pkg/cache/add.go#L77-L81) is in place, there are IMHO no benefits to keeping any history more that the commit your are looking for since nomad-pack cleans that up for you automatically after adding the registry

But i am more than happy to add the feature flag code if you are considering removing that code in the (near) future

2023-10-25 06:57 UTC, pkazmierczak commented
> as long as , [this bit of code](https://github.com/hashicorp/nomad-pack/blob/db9f7f8c84da83f267d9f6c4d1d103ba7c395a7c/internal/pkg/cache/add.go#L77-L81) is in place, there are IMHO no benefits to keeping any history more that the commit your are looking for since nomad-pack cleans that up for you automatically after adding the registry

Right! The team has been thinking about adding an [update feature](https://github.com/hashicorp/nomad-pack/issues/446) though, and I just thought fetching would be a natural way to do this. 

The more I think about shallow clones, the more I think this could just be an opt-out feature, as in: we'd default to a shallow clone.

2023-10-25 07:39 UTC, attachmentgenie commented
> The more I think about shallow clones, the more I think this could just be an opt-out feature, as in: we'd default to a shallow clone.

alright, will update to do just that

2023-10-25 15:29 UTC, pkazmierczak approved these changes
I've reconsidered, you're right. Shallow-clones are the way to go. Vide https://github.com/hashicorp/nomad-pack/pull/447#pullrequestreview-1697680506

2023-10-25 15:53 UTC, merged